- id: fuel-plugin-django-app_role
  type: group
  role: [fuel-plugin-django-app_role]
  tasks: [hiera, globals] 
  parameters:
    strategy:
      type: parallel

- id: fuel-plugin-django-app_postgres
  type: puppet
  groups: [fuel-plugin-django-app_role]
  requires: [hiera, globals]
  parameters:      
    puppet_manifest: "postgres.pp"
    puppet_modules: "/etc/puppet/modules/"
    timeout: 1800

- id: fuel-plugin-django-app_create-env
  type: puppet  
  groups: [fuel-plugin-django-app_role]
  requires: [fuel-plugin-django-app_postgres]
  parameters:
    puppet_manifest: "create_env.pp"
    puppet_modules: "."
    timeout: 3600

- id: fuel-plugin-django-app_deploy-app
  type: puppet  
  groups: [fuel-plugin-django-app_role]
  requires: [fuel-plugin-django-app_create-env]
  parameters:
    puppet_manifest: "deploy_django_app.pp"
    puppet_modules: "."
    timeout: 3600

- id: fuel-plugin-django-app_supervisor
  type: puppet
  groups: [fuel-plugin-django-app_role]  
  requires: [fuel-plugin-django-app_deploy-app]
  parameters:      
    puppet_manifest: "supervisor.pp"
    puppet_modules: "."
    timeout: 1800

- id: fuel-plugin-django-app_nginx
  type: puppet
  groups: [fuel-plugin-django-app_role]  
  requires: [fuel-plugin-django-app_supervisor]
  parameters:      
    puppet_manifest: "nginx.pp"
    puppet_modules: "."
    timeout: 1800